[package]
name = "voxel-ray-tracing"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.28"
winit = "0.28"
wgpu = "0.17"
env_logger = "0.11"
log = "0.4"
pollster = "0.3"
fastrand = "2.1"

egui = "0.23"
egui-wgpu = "0.23"
egui-winit = "0.23"
