[package]
name = "native"
version = "0.1.0"
edition = "2021"

[dependencies]
engine = { path = "../engine" }
winit = "0.28.6"
wgpu = "0.15.1"
env_logger = "0.10"
egui = "0.21"
egui-wgpu = "0.21"
egui-winit = "0.21"
pollster = "0.3.0"
glam = "0.24"
